project:
  type: website
  output-dir: docs

website:
  title: "Katie Ryan's Portfolio"
  description: "Landing page for Katie's portfolio, including various projects."
  site-url: "https://KateRyan.github.io/Portfolio/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: Flatly
    toc: false

editor:
  mode: source